-- Run this in the Supabase SQL Editor

create table public.calls (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  call_id text unique,        -- Retell Call ID
  caller_number text,         -- Customer Phone
  transcript text,            -- Full text
  summary text,               -- AI Summary
  lead_score integer,         -- 0 to 100
  status text default 'New',  -- 'New', 'Urgent', 'Qualified', 'Spam'
  recording_url text          -- MP3 Link
);

-- Enable Realtime
alter publication supabase_realtime add table public.calls;
